### ISSUE TITLE
Unexpected token export when running npm test

### ISSUE THREAD

**Issue by petecuttriss** [Voitanos/jest-preset-spfx-react16#1] opened 2018-12-12 21:04 UTC
Enivronment:  SPFx v1.7.0, Node.js 8.14.0 (x64) and NPM 6.4.1.

Hi Andrew,

Thanks for putting this together, it speeds up and eases the initial project setup so you can get to writing your tests. It also helps by removing errors caused by missing out key configuration steps.

In striving to do more unit testing and TDD, I’ve worked through some of the great blog posts and examples that both Elio Struyf (https://www.eliostruyf.com/... and Velin Georgiev (https://github.com/VelinGeo... have put together, and now using your preset package this has helped speed things up and reduce the error risk by making things even more reproducable.

When I initially start writing and running tests everything is fine. However once I start to include components from the core Microsoft library, things start to fall over. In my case I was adding a reference to the ‘Environment’ and ‘EnvironmentType’ enum from the `@microsoft/sp-core-library`. After adding this (or other references e.g. DisplayMode etc.) I would start to see an error when running my tests ‘Unexpected token import’ \node_modules\@microsoft\sp-core-library\lib\index.js:11 export { default as _BrowserDetection } from './BrowserDetection';. This has been noted in an issue posted to the sp-dev-docs Github repository (https://github.com/SharePoi.... To reproduce the problem I simply took your example test "Sample.tsx" and added a reference to the `EnvironmentType` from the `@microsoft/sp-core-library` library.

Using your jest-preset and some more research I’ve finally managed to get it all working, but I’ve still needed to make the following tweaks.

1. In the jest-preset.json file I’ve altered the “transform” configuration by adding “js” e.g. it is now 

```json
"transform": {
"^.+\\.(js|ts|tsx)$":
"ts-jest"
},
```

2. In the jest-preset.json file I’ve had to add a “transformIgnorePatterns” configuration as follows:

```json
"transformIgnorePatterns": [
"node_modules/(?!(@microsoft/sp-core-library))"
]
```

3. In the tsconfig.json file I’ve had to add an “allowJs” configuration item with it’s value set to “true” and remove the “declaration” configuration value (https://www.typescriptlang....

With the changes above I can successfully run tests against components which include references to the sp-core-library and can build, test and run my components. I must admit I don't fully understand the implications of my changes so I now need to do further research. It would be interesting to know if you’ve hit this problem at all also?

Thanks again for putting this together. 

Github Repo Reference: https://github.com/petecuttriss/spfx-jest-preset 

Regards
Pete

**Comment by andrewconnell** [comment] 2018-12-12 21:17
Thanks... I can repo. Investigating...

**Comment by andrewconnell** [comment] 2018-12-20 22:12
Update - I understand *why* this is happening, but I can't figure out how to fix it for a bigger set of circumstances. 

It's easy to fix for just the one library you're using, but this will quickly turn into a +1 issue when someone uses another library, so I'm looking for a more dynamic solution... this is affecting all three of my presets... 

Still working...

**Comment by petecuttriss** [comment] 2018-12-20 22:46
Understood.  Have a merry Christmas Andrew!  Thanks again for your all help.

**Comment by andrewconnell** [comment] 2019-01-03 19:23
Something occurred to me: What you're trying to do won't give you desirable results. You're trying to use the `Environment` & `EnvironmentType` objects that won't yield desirable results outside of a SharePoint context.

You should be able to just add the following in your spec file to tell Jest to mock those two objects without any changes to the jest config file:

```js
jest.mock('@microsoft/sp-core-library/', () => {
  return {
    'Environment': {},
    'EnvironmentType': {},
  };
});
```

I'm going to close this issue for now, but still working on a more robust solution in the case where it appears as an issue in other projects.

**Closed by andrewconnell** 2019-01-03 19:23 UTC

**Comment by taranxd** [comment] 2019-05-03 08:49
I am facing the similar issue and writing the above code didn't fix the issue :(

**Comment by andrewconnell** [comment] 2019-05-03 10:50
@taranxd please open a new issue with more details to better track the issue.

I became aware these presets are not working with the latest SPFx and need to investigate the root cause. Learned about the issue this week so will look into it shortly...

**Comment by jmunozcastro** [comment] 2020-09-03 19:04
Hello @andrewconnell, I am working implementing jest in some SPFx projects and I get the same error that explain @petecuttriss, the difference is that I am working with SPFx Framework v1.11 Do you have found another solution @andrewconnell or @petecuttriss? I appreciate so much the help ;)
